---
- hosts: all
  become: yes
  remote_user: istudmask
  gather_facts: true

  vars:
    db_user: finalmdauser
    db_password: finalmdauser12345
    db_name: finaldb

  pre_tasks:


    - name: "App update"
      shell:
        cmd: "apt update"
 
    - name: "Install packages"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql-12
        - postgresql-client-12

  tasks:
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
