---
- name: Install full PHP 7.4
  ansible.builtin.apt:
    name:
      - php7.4
      - php7.4-fpm
      - php7.4-cli
      - php7.4-mysql
      - php7.4-curl
      - php7.4-gd
      - php7.4-mbstring
      - libapache2-mod-php7.4
      - php7.4-readline
      - php7.4-opcache
      - php7.4-common
      - php7.4-json
    state: present
  tags:
    - php
