---
- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: latest
  when:
    ansible_os_family == "Debian"

- name: enable and start bind9 service
  systemd:
    name: bind9
    enabled: yes
    state: started

